### ISSUE TITLE
Fixed Interest rate as a reward

### ISSUE THREAD

**Issue by Polype01** [kinecosystem/rewards-engine#27]
There should be a way to retribute KIN hodlers with an interest rate. KIN is a currency so as a currency, I expect basic ecocnomics concepts such as interest rate and this can be automatically included in the KRE.

- KIN hodler would send its public adress to KIN Foundation
- There would need to be a KYC to avoid abuses (1 same user receives the interests)
- Every month, KF determines and distributes to the KIN hodler address 3% of the stash automatically 
 
- This should be targetting only Hodlers that have acertain amount of KIN 1B as a minimum
  This would incentivize people who have less than 1B KIN to buy KIN to reach that threshold, 
  increasing the speculative demand
- This should not target developers as they will be receiving already plenty of KIN via the KRE
- This would definitely limit individuals to dump their KIN on exchanges. There would be finally an incentive to hold KIN
- This would diminish a bit the increase of circulating supply as users would have a reason to hold KIN (and if users buy KIN to get to that 1B threshold
- This interest rate will be decreasing over time from 3%, 2,5%, 2%, 1,5%....

To me, this would help stabilizing the value of KIN and increase the speculative demand

**Comment by kikengineering** [comment]
Thanks again for your feedback and ideas.

The idea of interest or payouts similar in size to interest manifested itself in our Holding section of KRE 2.0. The main problems we saw with directly paying interest (besides possible regulatory concerns we would need to look into) were the following:
- Do we have enough Kin to pay a fixed interest rate for everyone? If everyone wants to hold Kin, and it gets put into 1B Kin sized wallets, we have to have enough reserves to this.
- More importantly though, let's say we pay a 3% annual interest rate on an account. The inflation rate in the Kin Economy is much more than 3% (on the order of 20% annually) so if a holder was not interested in holding Kin long-term they will likely still decide to sell regardless of whether or not the 3% interest rate existed.
- If we set a minimum on the amount of Kin that must be held in order to get interest we will likely see collusion.

By limiting the holding payouts to developers as in our Holding section, we were limiting the pool of wallets we would need to pay Kin. Additionally, we believe the "game theory" that will arise from potentially getting a huge payout (up to the equivalent of a 50% annual interest rate) if other developers do not hold will create strong holding incentives for developers.

**Comment by Polype01** [comment]
Hi Tanner (I guess it is you)

The idea here is to distribute and not paying :)
It could be a lower interest rate, even symbolic that would motivate people to buy KIN and reward KIN holders. Not all users have 1B or more KIN. 1-2% maybe? Also, the amount of KIn interests to distribute needs indeed to be limited in time and to decrease overtime. KIN demand will increase and we need it a bit 

You have Trillions of KIN so yes you have enough and especially on a small limited period of time. Or you could distribute an annual interest (lower than 20% - under inflation)if the user can prove that he held KIN on an account 1y without moving a certain amount of target KIN (again proposing 1B), he would get at the end of the 1y period 150M KIN.  Again it is just an example. To be calculated for a fixed amount. Also if you think of it, if more people hold their KIN, there will be less KIN flowing in the ecosystem so people/devs would buy more from external sources

**Comment by Polype01** [comment]
If a user wants to dump millions of KIn at once, a small interest rate will maybe not prevent him/her to do it but at least, he/she will think a bit before doing it if there is an interest rate and it would be already less KIN dumped on exchanges and a bit less circulating supply

**Comment by TheBubblePopped** [comment]
- There would need to be a KYC to avoid abuses 

Privacy is a concern, i don't want Kin/Kik or someone getting that DB through a leak, hack, w.e. know who i am and which pubkeys belong to me. 

- Every month, KF determines and distributes to the KIN hodler address 3% of the stash automatically

The compound interest would be 42% after 1 year. That's way too much. This would cause deflation for sure, especially in an ecosystem where apps haven't figured out yet how to [make users addicted || create earns & spends].

- This should be targetting only Hodlers that have acertain amount of KIN 1B as a minimum
This would incentivize people who have less than 1B KIN to buy KIN to reach that threshold,
increasing the speculative demand

That's not fair. Imagine banks giving interest rates only to the upper percentile. People would lose their minds. 

- This should not target developers as they will be receiving already plenty of KIN via the KRE. 

If i had an app the first thing i would do is tumble my coins through other wallets to make them look like they don't belong to me any more so i can also gain that interest rate. You can't blacklist that Kin, because to be a currency you must be fungible. There are also ofc other problems on how to track that Kin.
Also... just in theory, like really just in theory: Developers earn because they put an effort X in Kin. Why wouldn't they get a interest on their Kin? If the goal is to make users hold Kin instead of selling you would target rather bigger wallets that are selling, which again might be KRE receivers. The "devs are getting already plenty of kin" is not an excuse, you could argue/say the same about those buying at these levels now. 
Besides that, i also think that it could make devs feel excluded from the community as a whole, which could have severe implications.

An interest rate could also be seen as an airdrop. I've seen many projects doing airdrops and most of the time people just sold that airdropped percentage immediately. 

-To me, this would help stabilizing the value of KIN and increase the speculative demand

I thought speculation is not what we want, it's all about real usage. At least this has been the mantra till now. No?
