### ISSUE TITLE
KIN KRE 2.0 extension of Holding

### ISSUE THREAD

**Issue by Polype01** [kinecosystem/rewards-engine#35]
>  While the Spend and Buy tracks incentivize an increase in buy-pressure, we are also proposing an incentive tied to a reduction in sell-pressure in the form of a holding reward for developers.

It would be great to have that holding reward to all holders (developers and private investors)

**Comment by kikengineering** [comment]
Thanks for the feedback.

This may change in the future, but the reason for proposing this direction was to keep the KRE as a whole as close to neutral in terms of buy/sell pressure as possible. KRE payouts are one of the main sources of inflation in the economy, and developers (unlike a private investor looking at the long game of Kin) may need to sell Kin in order to offset operational costs. We wanted to focus on this group and make incentives to hold as strong as possible and give payouts on the same order of magnitude as the Kin inflation rate. Our rough projections lead us to believe that we would not be able to pay enough to get developers to hold if we also paid private investors from this KRE pool.

**Comment by Polype01** [comment]
I regret this decision as it would have helped limiting (a bit) the dumping of kin on markets by the speculators/investors and this would have given some extra perspectives for big holders in the mid term.

**Comment by hitwill** [comment]
Issue does not affect current KRE (closing)
