### ISSUE TITLE
Better rewards formula (hopefully), and some other thoughts.

### ISSUE THREAD

**Issue by harrywinkler** [kinecosystem/rewards-engine#5]
Kin: Great job on this Rewards Engine paper. And great idea looking for feedback.

Everyone: I think unique users will be very important, and I think I read somewhere that identity management is in your plans. The following formula(s) expects there to be a decent, Kin Foundation-approved identity verification scheme in place. Or at least a way to make sure apps have approximately no more than one user per person.

The way the paper currently stands, I see three main issues: whales are given too much weight, apps will all be incentivized to game transactions and create a lot of volume in order to be the "most preferred service" for each individual, and there is no mechanism to incentivize app developers to bring in users who are totally new to the ecosystem.

In giving less weight to whales (who otherwise have a large incentive to give themselves Kin Rewards and avoid inflation) and more weight to new users, I think apps new to the ecosystem will have a much greater incentive to join. The goals of these changes are more new users, more apps, and less whale power (which should mean more rewards for more apps). I don't think there's any reason to give whales a outsize incentive to pay themselves or their "pet" apps.

There are a few changes to the current paper that I think can help alleviate these issues:

1. In order to stop the gaming of the transaction volume of individuals by apps, perhaps a simple solution would be to split up the stake amount for each user equally among all apps used by the user each day. So a user with 500 Kin who uses 5 apps on a certain day will have 100 Kin staked to each app, no matter the transaction number or volume for each app.

2. In order to lessen the power of whales, but still give them influence and also encourage them to be active on multiple apps (instead of just one), the square root of all Kin staked to each app for each individual user will be calculated to determine the final stake amount for each app. In the example above, the final stake amount for the user would be 10 for each of the five apps. Total final stakes are added up to find the total SSEi  for each app, and the SSEi for all apps are added up to find the TSE. Everything else would be calculated the same.

3. In order to encourage users who are totally new to the Kin ecosystem, Kin should consider a specific reward that incentivizes new users. A scheme to do this could look something like this: All app's users who have transacted in Kin will be checked each day (if this is too tedious it could be a weekly or monthly reward... Kin could also force apps to keep track of their own new users, and only allow those to be submitted) against a list of users who have already transacted in Kin. Every new user that an app has is one point. You could be a new user of multiple apps on one day, in which case all apps that you participated in would get a point. But after that day, ideally, no one would ever receive a point for that user again. All apps would receive a reward proportional to their points, compared to the total points for all apps. The Rewards Engine based on the stake of Kin would still be the main reward, since it has to do with an amount of Kin, rather than what could possibly be an insignificant amount Kin. A possible allocation for this new user system could be as follows, given that new users are more important at Kin's start rather than later:

(Through month) - (Reward allocation of total reward, not the marketing and operations budget)
6 - 50% to Staking Rewards, 50% to New User Rewards.
12 - 60% to Staking Rewards, 40% to New User Rewards.
18 - 70% to Staking Rewards, 30% to New User Rewards.
24 - 80% to Staking Rewards, 20% to New User Rewards.
30+ - 90% to Staking Rewards, 10% to New User Rewards.

Another question: how will crypto exchanges be handled? Are they exempt from the rewards engine? Otherwise, if they game it at all, they could end up getting a nice chunk of the rewards.

Another opinion: I think all apps should be automatically approved and the community should be relied upon to flag any app for Kin Community violations, because manually approving apps would take to long (and an app can be changed at any time). Have an open book of which apps got Kin rewards each day, from greatest to least, and the reason why (anonymized lists of users, number of users, number of new users, wallet levels of users, and number of apps used per user). I think the biggest problem apps will be called out quite quickly.

Small issues:

1. The paper states, "Dilution of the rewards will occur but needs to be controlled so as not to shrink the rewards given to legitimate digital services." It should say, "not to *significantly* shrink".

2. "On the other hand, increase in supply is assured as a guaranteed annual influx of 20 percent of the reserve." Just before this you state that the Foundation can change the inflation rate, I believe. So this could be qualified with the following at the end of the sentence, "(Unless the foundation changes the inflation rate)"

3. "To enable this goal, Kik will opt out of participation in the rewards mechanism for no less than 12 months from time of the Rewards Engine launch, passing it on to 3rd party developers of Kik bots." The last phrase should instead say "passing on any rewards that would otherwise go to Kik to 3rd party developers of Kik bots." This change should make it clear that apps other than Kik bots, like those entirely outside of Kik, can get rewards.

This is food for thought that may or may not be used. Hopefully people feel free to expand on this stuff and/or debate it. I am a Kin investor. Thank you!

**Comment by odednoam** [comment]
Thanks @harrywinkler for the input! Sorry I didn't answer immediately, was travelling and just got back to the office.

I'll write my current view on your suggestions, and will give it some more thought in the coming few days so I may comment again.

About the proposed changes:

> 1. In order to stop the gaming of the transaction volume of individuals by apps, perhaps a simple solution would be to split up the stake amount for each user equally among all apps used by the user each day. So a user with 500 Kin who uses 5 apps on a certain day will have 100 Kin staked to each app, no matter the transaction number or volume for each app.

We wanted to have a single _favorite app_ per user, in order to promote a "winner takes all" incentive - which is probably a stronger incentive (this intuition is also backed by some [research](https://www.chapman.edu/ESI/wp/Sheremeta-Winner-Take-All.pdf)). Since publishing the RFC we have heard some criticism on this (including some research about [winner-takes-all incentives and foul play](https://www.psychologytoday.com/blog/work-matters/201006/winner-take-all-incentive-systems-competition-and-cheating-teachers-soccer)) , and I do think your idea of equal sharing of the vote has a lot of merit. So, I will look into it!

> 2. In order to lessen the power of whales, but still give them influence and also encourage them to be active on multiple apps (instead of just one), the square root of all Kin staked to each app for each individual user will be calculated to determine the final stake amount for each app. In the example above, the final stake amount for the user would be 10 for each of the five apps. Total final stakes are added up to find the total SSEi for each app, and the SSEi for all apps are added up to find the TSE. Everything else would be calculated the same.

Having voting power sub-proportional to stake is ideally a good thing (if you take it to the extreme, it is "one person - one vote"). But we don't want to impose any restrictions on ecosystem partners, and proving that each "user" is indeed a since unique person in the real world, via KYC or whatever method, is a something that many digital services wouldn't want to have - simply because it's not required for their core functionality. If you have no proof that each user is a unique person, any system in which voting power is less than proportional to stake is essentially giving incentive to cheating by Sybil attack (splitting stake between fake users) because it increases one's voting power.

> In order to encourage users who are totally new to the Kin ecosystem, Kin should consider a specific reward that incentivizes new users. ...

We gave a lot of thought to this, as this is indeed a very important goal of ours. The challenge here is double: one, is that we don't want to impose any KYC on digital services joining the ecosystem, so it is very hard to protect against _fake new users_. Also, too much incentives to digital services in their *growth* phase come at the expense of established services -- and we really should be cautious not to incentivize growing services to be part of Kin but then leave as soon as they're established. While the latter problem can probably be mitigated through careful tuning of the relative size of the incentives, the former is something we're still looking for a solution to, and if you or anyone can propose a solution it will be most helpful.

**Comment by harrywinkler** [comment]
Thanks for the response, @odednoam. I really appreciate it. Everything you're saying sounds good to me. Winner takes all is great, but it can be gamed. If you like winner take all, you could just have the user choose the winner any time they use more than one app in a day. That should get rid of the incentive to game transaction volume.

In regards to the KYC issue, I think in the long term you will find a solution that may satisfy KYC for digital services joining the ecosystem that is so easy-to-use it's not too big of a barrier for those services. In the short term there could be an easy, temporary solution for all of this: you could favor ICO investors, since they supported the Kin Foundation with funds rather than investing later, and they've already been through KYC. The KRE could give out a small, set reward for each wallet that doesn't have KYC (So that there would be little or no benefit in faking those accounts), and that will be all wallets that aren't registered for the ICO. But any ICO registered wallet gets the full reward and, even though they're not really new to the ecosystem, ICO wallets could initially determine the bulk of the new user reward for apps if you implement a reward like that as well. However, maybe that won't make sense since Kin ICO investors aren't really new users. The summary is that perhaps you could have KYC perks only for ICO investors, and then gradually add optional KYC perks to those apps that go forward with KYC once you add that functionality.

**Comment by harrywinkler** [comment]
Worst case scenario you could still lessen the influence of Kin whales by taking the square root of any staked (wallet) amount. This would help even without KYC, because sure, they could make a ton of wallets, but at least it would be a big pain to do so... And then they have to create transactions with each of those wallets in the app, every single day, which would also be a pain. Anyone who could automate that would probably be getting good practice for creating a real app that scales and then they might actually launch a good one so they can earn more of the KRE rewards. Just some more thoughts.

**Comment by odednoam** [comment]
As far as I know, there is no policy change i.r.t. Kin being a decentralized platform in which participating services are autonomous to shape their own worlds. 

Inside Kik, and because Kik believes it should provide its users with safe experiences, wallets will be associated with Kik accounts. So if someone is doing something illicit using Kin inside Kik, they will be dealt with. What happens in other apps in the Kin ecosystem is, of course, up to the administrators of these apps.
