### ISSUE TITLE
Only earn KRE when you have at least 1 spender in that period

### ISSUE THREAD

**Issue by l-hendriks** [kinecosystem/rewards-engine#57]
With the hold track you can basically pull the app off the ecosystem and earn more Kin in perpetuity if you don't sell your Kin. I'm not sure if that is intended with the hold track, as that specific app doesn't add any value to the ecosystem anymore. I propose to update the KRE so you are only eligible to earn Kin when you have at least 1 spender (or earner) in that specific period.

**Comment by kikengineering** [comment]
Thanks for taking the time to post.
There is actually a line that addresses this in the KRE:
https://github.com/kinecosystem/rewards-engine/blob/master/current-KRE.md
'Note that a developer will only be rewarded KRE payouts for days where at least one Kin blockchain transaction took place in their respective application.'
So right now, if a developer has a single earn, spend, create or p2p transaction in their app in a day they can be rewarded for any of the three tracks.
We had some internal discussion and thought this was the simplest and best approach for now (happy to discuss and support if you think this can be improved).

It is a bit difficult to discern when an app has officially "left" the ecosystem and should be excluded from the KRE. We've had some internal discussions about potentially proposing a change that would force a developer to currently have Kin in a version of their app available in one the major app stores in order to get KRE, but shelved the idea for now because there seemed like too many edge cases where this was not appropriate. At minimum, even if there may be better ways to use the Kin, if the KRE is rewarding someone who is holding Kin (even if they are not actively participating in the app economy) the Kin is still incentivizing some sort of positive behaviour.

**Comment by l-hendriks** [comment]
Thanks for the clarification, I completely read over that line! In that case I think this is fine as it is :)
