### ISSUE TITLE
KRE 2.1 Demand track 

### ISSUE THREAD

**Issue by showered** [kinecosystem/rewards-engine#63]
Under KRE 2.1, the demand track was modified so that the total "demand" must be higher than the previous all time high in order for the app to receive KRE for this track. That's my interpretation anyway. 

Therefore, if a user topped up their app wallet with 10 billion Kin. Then, the next day, they moved their 10 billion away to another wallet. Then the app in question wouldn't receive a single KRE payout again for the demand track, until the total demand goes above and beyond 10 billion. 

Is this right?

If so, it would be quite easy to sabotage. 

@kikengineering

**Comment by kikengineering** [comment]
Hi Showered, no, the scenario you described wouldn't work out quite like that.

Assuming a user wallet in the app gained 10B kin one day, then yes, the app would be paid for the 10B Kin demand in the app for one day. However, this would be much less than 10B Kin since the total that can be paid to the buy track per day is currently 30MM Kin. Suppose 10B was 1/3 of the total demand of all apps that day, then the developer would be paid 10MM Kin for this demand.

If all of the Kin then left the user wallet then yes, the demand track isn't paid again until the demand for that passes a threshold, but that threshold is how much they have been paid in the buy track (10M kin) and not how much the highest demand ever was. So if the app produced 11MM more demand, they would be paid for the "new" 1MM demand.

It does punish Kin leaving your app, but it is not that aggressive and only punishes for what you have been paid for. In order for the scenario you described to happen, the 10B kin would need to sit in the app for a sufficiently long time such that the developer was paid the full 10B Kin (that would take months). In that case, then yes, the developer would need to overcome 10B Kin of demand in order to be paid again, but they would have been paid 10B Kin by Buy Track of the KRE.

**Comment by showered** [comment]
Thank you so much for your clear explanation.
