### ISSUE TITLE
Kin Improvement Proposal V3 Discussion

### ISSUE THREAD

**Issue by kikengineering** [kinecosystem/rewards-engine#87]
@hitwill

Overall. the proposal has a lot of great ideas and the general direction makes a lot of sense: removing the hold track and inserting developer holdings as a multiplier both further incentivizes developers to hold while simplifying the calculations. Below are a few comments and open questions for further discussion:
1) Buy Ratio can be replaced by Kin Bought without any changes to the output. This will make the buy part of the equation more analogous to the GDP part.
2) "i" should probably be replaced with "j" on either the top or bottom half of the equation.
3) How specifically is GDP calculated? Is it:
Sum( if amount > 1000 then 1000 else amount) of all p2p and spend transactions?
If a pair of users pass 1000 kin back and forth 10 times in one day, does that count as 10,000 in GDP?
4) Will holding be capped in any way by prior KRE payouts? I.e. can a developer simply purchase a large chunk of kin to increase payouts?
5) Given the above, do we need additional incentives to allow newer developers to properly compete?
6) The multiplication by Hr feels a bit too aggressive (doubling your holdings by purchasing Kin would double your payouts). Log (assuming Log(Hr) was meant to be the ratio of the logs of the holdings) feels like it does not do enough (unless the base of the log is quite small). I would propose something like the ratio of the square roots of the holdings as a more reasonable middle-ground: doubling one's holdings could increase payouts by 40%.
7) This description removes the concept of capping buy payouts at the amount of Kin actually bought (i.e. under this proposal, all payouts would be paid out every day).

Thank you for putting this together. There will be some great discussion that comes from this.

**Comment by hitwill** [comment]
https://github.com/kinecosystem/rewards-engine/issues/87

Thanks for the feedback, @kikengineering . These were just some thoughts I had and I put them out for discussion. To your points:

> Buy Ratio can be replaced by Kin Bought without any changes to the output.

Could you elaborate a little more on this point? It's currently as a ratio so that app i's purchase is relative to app j's purchase.

> "i" should probably be replaced with "j"

This makes sense, to keep with the formalism used. I will clean that up

> Sum( if amount > 1000 then 1000 else amount) of all p2p and spend transactions?

Yes that is more precise. I should add a more formal/ algorithmic description

>If a pair of users pass 1000 kin back and forth 10 times in one day, does that count as 10,000 in GDP?

It would formally count. (It could be users betting on an app like Peer Bet). However, you are right that apps could game it by sending Kin back and forth. I think this vector would be present in most forms of rewards. 

> Will holding be capped in any way by prior KRE payouts

This is a good point. I think there shouldn't be a cap on holding (since holding benefits the ecosystem at large and allows for long term commitment). However, the Kin issued to Kik originally at the TDE probably shouldn't count.

> Given the above, do we need additional incentives to allow newer developers to properly compete?

This definitely warrants some thought. (Especially in the long term, after older apps have accumulated a significant amount of Kin). This is a similar challenge faced by incumbents in staking systems, which they solved through staking pools.

> I would propose something like the ratio of the square roots of the holdings as a more reasonable middle-ground: doubling one's holdings could increase payouts by 40%.

There's definitely a goldilocks zone somewhere. I agree that doing it without a log or root is a little aggressive. I suppose the balance should rest where an app feels it's profitable to hold more, but not *too* profitable that it causes a runaway monopoly.

> under this proposal, all payouts would be paid out every day

Could you elaborate a bit more on this?


Thank you for the feedback. I will try to flesh it out a bit more over the weekend.

**Comment by kikengineering** [comment]
> Buy Ratio can be replaced by Kin Bought without any changes to the output.
Specifically, let B_i be the amount of Kin Bought through modules in an app. Then,
B_r_i = B_i / (sum for all apps k B_k)
This (sum for all apps k B_k) exists as the denominator in every term on the top and bottom of the equation, and can be factored out and cancelled. A similar logic can apply to replace H_r_i with H_i on both sides of the equation. It just feels a bit odd to compare the total GDP in one half of the equation, while we compare ratios of Kin bought in the other.

> under this proposal, all payouts would be paid out every day
This was referring to the fact that the KRE currently caps each track at a specified amount: the spend track has a max per spender (though this is no longer relevant), the hold track caps out at payout equivalent in size to a 50% annual interest rate, and the Buy track is capped at the amount of Kin bought through modules. Would/should a similar system still exist in your proposed solution?

**Comment by hitwill** [comment]
> A similar logic can apply to replace H_r_i with H_i on both sides of the equation

Ah I understand what you mean. Yes, your statement makes perfect sense.


> This was referring to the fact that the KRE currently caps each track at a specified amount


I think it depends on the reason for capping. The way I see it, as long as an app is doing a behavior that benefits the ecosystem, it should be incentivized to keep doing so - Up to the point that it doesn't monopolize KRE rewards. Perhaps, instead of individual caps, just a general Monopoly cap? (Like in previous KRE's).


So that as long as long as a single app hasn't hit a monopoly cap, it can keep increasing earns by buying more, spending more or holding more.


I appreciate this feedback. I am sure there will be other proposals, but it at least helps me refine this one. Perhaps the final proposal will come from different ideas from different participants.

**Comment by Ghost-Type** [comment]
hello thank you for addressing so many issues with kre3

one small suggestion would be to move away from using coinmarketcap for price calculation, as it is highly unreliable, especially during times of high volatility. for example legitimate exchanges are excluded from the average when they rise too rapidly, and unsavory exchanges are sometimes randomly included to inflate the price to appear higher than it is, affecting all payouts using this calculation method. i think the average price between the top two exchanges (combined liquidity x volume)(bg and gate) would be more appropriate, and as more reputable exchanges are added they should be added to the pool to create a custom pricing oracle for the kre.

i've also created an additional issue for consideration:
https://github.com/kinecosystem/rewards-engine/issues/90

**Comment by hitwill** [comment]
Closed as V3 already implemented - good suggestions all round
