### ISSUE TITLE
kik_kre_3_0 Discussion

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/rewards-engine#91]
I like option 2 of the proposal - seems to cover a lot of the attack vectors the others have. (Gameability through low quality transactions, and using ghost accounts to pump rewards)

**Comment by hitwill** [comment]
For this proposal, why is an active wallet defined as 1 month? (Why not 1 week or 1 day) - Just curious about the rationale

**Comment by MAli80** [comment]
I agree that KRE 2.2.2:
•	Does not discriminate between “high-quality” and “low-quality” spends
•	The KRE payout logic is complex

Regarding “Option ii. Active User Wallet Balances”, I believe there are **serious issues** with this proposal:

- The new KRE does not discriminate between “high-quality” and “low-quality” spends (same as KRE 2.2.2). so it can’t be considered an enhancement
- The new KRE logic encourages developers to have totally isolated economy for each App; In order to maximize the new KRE payout:
              - The developer will not to allow sending of KIN outside their application to an external wallet or moving KIN between apps.
              - The developer will discourage spends to the minimum (only to be counted as MAS).  In a natural/real life economy, the 
                  result will be recession!
              - Very easy to manipulate, just fund user’s wallets and encourage minimum spends to be counted as MAS.

**Comment by MAli80** [comment]
I believe KRE 3 can be enhanced by introducing another variable that gives the App a score of its KIN ecosystem implementation. 
Whenever an application developer changes his KIN integration features, He will submit a form/request to KIN foundation, KIN foundation will give the APP a score based on specific & well known metrics for integration For example let App_KIN_Score be 0.0 -1.0
`App_KIN_Score=0

if (Application allow KIN to move to/from other Apps) :
       App_KIN_Score+=0.2 

if ( Application allow KIN to move to/from external wallets) 
      App_KIN_Score+=0.1 

if ( Application has implement a buy module):
      App_KIN_Score+=0.2 

if ( Users are aware of each spend and the amount ):
       App_KIN_Score+=0.3 
.....etc`

**Comment by kikengineering** [comment]
Hi Will and Mali,

Thanks for taking the time to read through the proposal and comment.
@hitwill The primary reason for MAS as opposed to DAS was to remove the need for developers to create low-quality Kin use cases, where major portions of the app were locked via Kin which was quickly earned and subsequently spent. With MAS being the important metric instead, developers can hopefully focus on better experiences. WAS is a very reasonable alternative, but we lightly preferred MAS as it is more in line with all of our current ecosystem metrics and was the least restrictive option.

@MAli80 
> * The new KRE does not discriminate between “high-quality” and “low-quality” spends (same as KRE 2.2.2). so it can’t be considered an enhancement

While we do not directly discriminate against any specific use case what we tried to do was remove incentive to force users to spend every day. Developers are welcome to have any use case they desire, as long as users spend once every 30 days. We talked a lot about different ideas for minimum spends from users, but almost all added complexity/subjectivity which we tried to avoid.

> * The new KRE logic encourages developers to have totally isolated economy for each App; In order to maximize the new KRE payout:
>   - The developer will not to allow sending of KIN outside their application to an external wallet or moving KIN between apps.

We discussed this one at great detail (we've had similar feedback from others on this issue) and a proposed solution is would replace:
`A user is an MAS in app i if their last spend transaction in a KRE-app occurred in app i and was in the last 30 days. `
With
`A user is an MAS in app i if they spent in app i and was in the last 30 days.`
This may not directly encourage tourism, but it significantly lessens the blow of a user going to another app. What do you think about that?

>   - The developer will discourage spends to the minimum (only to be counted as MAS).  In a natural/real life economy, the
>   result will be recession!

Can you explain what you mean by this?  We agree that some developers may choose to decrease the amount of Kin being spent on products, but we think that this will be an improvement on the net demand for Kin being generated by KRE apps.

>   - Very easy to manipulate, just fund user’s wallets and encourage minimum spends to be counted as MAS.

We agree that if you get a large amount of Kin, fund user wallets with said Kin, and keep the users spending within your economy, then yes, you will continue to get paid by the KRE. However, Developers already exhibit this type of behaviour and get paid by the Spend Track of the KRE. More importantly, where will developers get this Kin from? If they buy it, that is positive demand, if users buy it, that is also positive demand, and if the developers use their KRE payouts to fund user wallets, then that Kin cannot readily be sold. We are not trying to diminish your comment about this attack vector (we are very aware this exists and will watch closely and propose updates if absolutely necessary) but almost all methods of developer increasing their KRE payouts would be an improvement on the current net demand for Kin being generated by KRE apps.

> App_KIN_Score

In terms of this idea, this and a few others were proposed in order to increase incentives for developers making compelling use cases. While we 100% agree that we wish to reward apps with the best use cases more, what we've found over the last year and a half of running the KRE is that anything with subjective monitoring is very challenging and we tried very hard to remove as much of this from the KRE as possible. It greatly increases the overhead of computing payouts as there is a large number of apps which make very frequent changes. All of these updates and changes need to be communicated to the payout team looking at blockchain data, and adjustments need to be made accordingly. More importantly, as the community continues to scale (as we hope it will) this will become increasingly difficult to automate and decentralize, and we will need a large team constantly assessing apps on a weekly basis.

**Comment by KkinC311** [comment]
Hey,

Reposting here from the Kin sub-reddit.

Total daily KRE payout shouldn't be directly linked to USD value and by taking the prior days close you open the door for someone to attack KRE payouts with little cost as you only need to affect 1 candle. I propose that you take the original idea of 20% of the remaining KRE balance per year, split it linearly over each day for the year then multiply it by the B/I ratio as the B/I ratio determines if the ecosystem is sustainable, a multiplier can then applied for early adoption that tapers off over a set period (say 6 months?). e.g. ((4.25 trillion* 20%) / 365) * 0.0126 = ~ 30 million per day

B/I ratio of 0.0126 taken from October's economy report

Average user wallet balance (AUWB) will discourage apps from allowing users to withdraw their balance or transfer it to another app which will impact the network effect and overall discourage apps from sharing users. Placing a requirement on implementing a transfer module to be eligible for KRE payouts would elevate this problem.

I personally prefer Hitwill's proposal however I would change the monopoly clause too the top 5 apps can't have more the 85% and no app can have more than 50% of the total payout. Would recommend using a track schedule similar to Kik's KRE proposal instead.

These proposals are an attempt to simplify KRE payouts but it still requires that an app must track the data of all other apps to determine their daily payout which I don't think we should expect them to do. The KF should create a KRE dashboard which abstracts the logic and data that allows apps to track their daily payout instead, numbers can still be verified by an independent if needed. 

The numbers I used above are arbitrary and should be modelled by someone with experience doing so before an informed decision can be made.

**Comment by kikengineering** [comment]
Hi @KkinC311, thanks for taking the time to read through the proposal and respond.

> Total daily KRE payout shouldn't be directly linked to USD value and by taking the prior days close you open the door for someone to attack KRE payouts with little cost as you only need to affect 1 candle. 

This is reasonable attack vector to address. The developer would need to decrease the price every day in order to adjust the payout so while we are not terribly concerned, we could certainly average the last 7 days of closing prices to mitigate risk.

> I propose that you take the original idea of 20% of the remaining KRE balance per year, split it linearly over each day for the year then multiply it by the B/I ratio as the B/I ratio determines if the ecosystem is sustainable, a multiplier can then applied for early adoption that tapers off over a set period (say 6 months?). e.g. ((4.25 trillion* 20%) / 365) * 0.0126 = ~ 30 million per day

While this would certainly reduce sell pressure from apps, we think there needs to be a balance here with keeping the game compelling enough for developers to still play. What you have recommended would be a very significant reduction in the daily payout (resulting in only 6% of what is currently paid). In the future, we hope to get to a place where the ecosystem apps drive more Kin bought than is paid out by the KRE, but if we push that direction too quickly, we think a lot of developers may leave the ecosystem. It also reasonable to have B/I ratio < 1 for some time as it is effectively a marketing fee. Developers are paid Kin to educate their users about the Kin economy.

> Average user wallet balance (AUWB) will discourage apps from allowing users to withdraw their balance or transfer it to another app which will impact the network effect and overall discourage apps from sharing users. Placing a requirement on implementing a transfer module to be eligible for KRE payouts would alleviate this problem.

It's a very reasonable addition to make. We discussed this exact option but left it out to keep things simple. Our post above also gives an idea which allows for more tourism between apps.

> These proposals are an attempt to simplify KRE payouts but it still requires that an app must track the data of all other apps to determine their daily payout which I don't think we should expect them to do. The KF should create a KRE dashboard which abstracts the logic and data that allows apps to track their daily payout instead, numbers can still be verified by an independent if needed.

While it's not perfect, the KRE has a dashboard for looking at payouts:
https://public.tableau.com/profile/kinfoundation#!/vizhome/KRE2_0NewDash/Dashboard1
We would like to make a similar one in the coming weeks so developers can understand any new KRE 3.0 system and adapt before January 1.

**Comment by Raketenernie** [comment]
Following things I would like to improve:





We recommend that the daily payout is the lesser of either 250 million Kin or USD $5000 worth of Kin per day:

That would be 150k Dollars rewards per months or 7.5 bn Kin per month, far too high and I explain why. Just take yesterdays volume on bithump, we had about 277 Mio Kin bought and over 300 Mio. sold, now providing an extra 250 Mio. per day would just increase the sell side and price erosion continues. So how do we tacle the amount rewarded there is very simple solution. Here it comes, first of all reduce the amount further according to the buy volume both in apps and exchanges. the B/I ratio covers that may be needs further fine tuning. Secondly and this is the clue the amount / quantity of reward is not set only to the activity and kin spind / bought but also of the total amount app Y has already gain / received. As more app Y has received through the KRE , the lesser will be the KRE.

**In Terms of a formular it has to look like this:

 **For app Y: TotalKRE(received)/TotalKRE(payouts)= giving you the factor "k"

--> So the monthly KRE payout to app Y --> KRE(amount for app Y)*k

This means apps like Rave and Co who already earned and hold more KIN then all exchanges combined, will not continue gain over-proportionally KIN. As they already hold a lot of Kin their incentive is set through holding kin and the fact the price gains of KIN, which absolutely seen with the cheer amount they already hold is very attractive.****



2. Active user balance

Do I understand it right you just want to look at user account balance over a period of 30 days?

If I understood it right then I can easily gamble that reward structure , I just need two wallets per user and make them send within 30 days KIN from A to B and the repeat month by month, simulating I was active and spending kin, which in fact I was not i just moved it.

Would it not better to reward the amount of transactions per account and even that could be gambled by bots? By the end of a day in the digital world activity can be faked by programs / bots and that is why rewarding "activity" is false.

KRE should only reward dollars spend for KIN and real spends of kin for physical / digital items. Both is measurable and cannot be gambled, the rest is just flawed and we know in fact auto spends and earn are right now in place and apps get reward for that, and that has to end.

**Comment by MAli80** [comment]
Hi kikengineering and thank you for taking the time to reply to our comments.

> While we 100% agree that we wish to reward apps with the best use cases more, what we've found over the last year and a half of running the KRE is that anything with subjective monitoring is very challenging and we tried very hard to remove as much of this from the KRE as possible. It greatly increases the overhead of computing payouts as there is a large number of apps which make very frequent changes.

I got your point and now I understand your perspective.
There will be never a perfect solution. We always have to find balance between complex solution that tries covering all possible flaws and simple solution that is open to many vulnerabilities.

As a balance/middle ground solution, I suggest to put a condition/incentive/check for top APPs only. For example:

An APP can only receive more than 10% of KRE if M out of N conditions are met:

1. The App implemented KIN discovery module
2. The App implemented 1 approved KIN buy module
3. The App implemented more than 1 approved KIN buy module
4. The App allow users to send KIN to their external Wallet
5. The App integrates with CODE API
.
.

The conditions must be objective with very clear Yes/No answer
This way you have to evaluate only very small number of apps for very clear conditions.

**Comment by kikengineering** [comment]
Hi @Raketenernie thanks for for your comments.
> That would be 150k Dollars rewards per months or 7.5 bn Kin per month, far too high and I explain why. Just take yesterdays volume on bithump, we had about 277 Mio Kin bought and over 300 Mio. sold, now providing an extra 250 Mio.

Firstly, we totally understand the desire to make the total Kin payouts smaller. If developers are rewarded less, then have strictly less to sell on the market, and the rate of inflation goes down. Having said that, what we have proposed is already a substantial decrease from our current payouts (from 500M/day to 250M/day or $5,000 whichever is less). Also, maybe it's changed the past few days, but looking at Bithumb, I see a 24h transaction volume of almost 2B Kin and the market is reasonably stable right now. We would argue the market seems to be dealing with the influx of KRE payouts at the current daily limit. We believe there needs to be a careful balance of making the KRE compelling for developers, while moving towards positive net demand for Kin. If we capped payouts today at the amount of Kin being bought by users the payouts would likely decrease very dramatically and we fear that many developers would leave the ecosystem.

> **In Terms of a formular it has to look like this:
> 
> **For app Y: TotalKRE(received)/TotalKRE(payouts)= giving you the factor "k"
> 
> --> So the monthly KRE payout to app Y --> KRE(amount for app Y)*k

I'm not sure I completely understand the math here, but it seems like what you are describing is diminishing rewards for developers the longer they participate in the KRE. While this definitely may incentivize newer developers, it would make it increasingly difficult for older/larger partners to continue with Kin and could shrink our ecosystem over time.

> 1. Active user balance
> 
> Do I understand it right you just want to look at user account balance over a period of 30 days?

We would look at a user's daily balance, for all users who had spent in an app in the last 30d. The loop holes you described can still be exploited, though they are strictly less valuable than they are today: developers need to get Kin into user wallets and have it be used by users in order to get rewarded from the KRE. The Kin in the user wallets needs to come from somewhere (users purchase, developer purchase, or from prior KRE payouts from the developer). All of those options reduce the amount of Kin being sold on the market.

> KRE should only reward dollars spend for KIN and real spends of kin for physical / digital items. Both is measurable and cannot be gambled, the rest is just flawed and we know in fact auto spends and earn are right now in place and apps get reward for that, and that has to end.

While we definitely agree we would like to get to this point someday, our fear is that is we push the KRE to do this now, we would make the KRE unplayable for most developers. We feel that this would not be in the long-term, economic best interests of the ecosystem. There is also a more subtle issue here: if we reward developers for users buying Kin, then if the users spend that Kin immediately after buying it, and the developer sells the Kin that was spent and is paid by the KRE and sells that, then the net is still negative demand for Kin. In the future, we need to reward the net flow of Kin into user wallets.

**Comment by kikengineering** [comment]
@MAli80 
Overall great idea which makes a lot of sense. If we were to go in a direction where we would do subjective monitoring as part of a solution (we may need to get there eventually as the ecosystem grows) this would be a good direction to go in: very simple rules and only apply those rules to the top x apps.

As it stands now, we would still push for a KRE 3.0 with no monitoring to begin with. We think we should first see how things go, and add on additional restrictions if necessary next year.

**Comment by Raketenernie** [comment]
Hello everyone,
Thank you for your response, I will repeat here, what I posted in the forum
which I think is essential and needs fixing.

Very important fact / issue all approaches left out:

What I saw so far, all proposals trying to fix the distribution of KIN over
the KRE by different methods. However , the ultimate challenge or problem
of the KRE is a different one. Which comes now , I explain:

The amount / the volume of KRE is the challenge. What we have seen (ex
-ante) is that over a period of a year the KRE has rewarded more Kin that
the ecosystem actually was able to absorb. Over time the KRE Reward System
oversupplied the ecosystem with KIN. One way to demonstrate this fact, is
looking at the Net Dollars Bought (NDB) which expresses the kin bought by
dollars for goods and services within the ecosystem, less all KIN paid by
the Kin Foundation through the KRE and grants. The NDB steadily decreased
reaching a new negative delta of 300+ Billion Kin.

To make it clear for anyone how big this oversupply is

Given ceteris paribus, even if you would stop KIN KRE right now, with the
current KIN spend per day (GDP) of 200 Mio. it would take 1.500 days (over
4 Years) to cover up the 300 billion of NDB in terms of oversupply.

So I beg you before you adjust the KRE distribution, create a mechanism /
formular which calculates the exact amount of Kin which can max. absorbed
per Month and fix the amount of KIN KRE rewards to that caculated amount.

To get this very simple a monthly oversupply of Kin , stays as a
oversupply, it will make no difference if you change the distribution.

This should be your priorities to optimize the KRE:

   1.

   Find / set the right amount of KRE rewards possible
   2.

   Push GDP
   3.

   Stop rewarding vectors which can be gambled,

There are 3 major vectors which will bring you value which are not easily
be gambled

   1.

   Dollars spend for kin, --> in app pruchases with Fiat
   2.

   Kin spend for Dollars , I do not think either of them two exist at least
   not large scale
   3.

   Tourism

Minor vectors are:

   1.

   Create valuable earns
   2.

   Create valuable spends

Dollars spend for Kin and Kin spend for Dollars would be two vectors which
can be measured and not be gambled and they would bring real value to Kin,
as KIN would become an intermediate of exchange for Fiat.

The other vectors are important too, cuz they are the reason ppl will spend
money for kin. However what does it help the ecosystem, if I create 100
spends but none of them gives an incentive to users to buy kin with their
dollars. Think about it , the ones who can convert the usage into real
economic value or money that are the ones you should really reward, they
are your gems.



I know you said , it is basically impossible to reduce payouts due to the
fact that for apps to participate gets less attractive. But this is a wrong
perception of the apps and that is why you have to well communicate it
should be in all common interest to reduce payments. Many of the apps right
now hold a lot of kin and it should be in all interest to increase the
value of kin. This can only happen if we stop the oversupply, sorry if apps
like Rave do not understand the underlying concept of creating scarcity of
kin then you have to explain. They will be the ones profiting the most of
this strategy once kin is on the climb. As more they hold as bigger the
reward will be for them.

I know there is fear apps would drop out and apps using Kin not for the
tech but for the "free" money, but we should ask ourself are these the
showcases of kin and are these the apps bringing real value to the
ecosystem, yes they got the numbers but not economic value, they have and
most likely will not bring real value to the table. I rather see 10 apps
bringing real value and spends to the ecosystem than having a
massive zombie app abusing Kins KRE. I go even further I predict you by
continuing the KRE oversupply will just delay your problem into the future
and the apps might not immediately drop out, but one day they will, as the
incentive to earn more kin has converted to 0. These are apps who are not
in for Teds vision nor for the foundamentals / tech behind it, no they are
in because of the money. So I rather see you fixing the KRE meaning there
will be some unpopular decision but if it means you heal the ecosystem and
actually create that scarcity and value for kin then let it be , then let
apps drop out. Others new ones will come and when they see the Kin I hold
today is worth more by tomorrow it becomes a positiv upward cycle.. This is
the basic principle why BTC is such a success, we know techwise it has
already seen its limit but because ppl not only speculate, but the history
of BTC show that BTC I hold today has a very good chance to be worth more
by tomorrow, has created a value for BTC and  an expected value for a
digital coin, whereas compared to KIN the expectation is way more
conservative prooven by its price performance. I can only advise to reduce
and peg the KRE reward to the max absobment level and also reduce the KRE
amount if the price of Kin rises, as this alone will signal to everyone kin
is becoming valuable.

An alternative way to reduce the KRE payments would be to freeze them / to
log them for a certain period of if a certain price level has reached or
best way if the ecosystem has matured and reached 10 bn KIN GDP per Month.
Like that no apps has lost KRE rewards they just logged for everyones
benefit, see it as banking and they get it when the ecosystem is mature
enough to absorb it.

Hope this enough to disscuss about.

Best Regards,

Henny

**Comment by kikengineering** [comment]
After listening to a lot of community feedback, we are pushing a commit to our proposed KRE 3.0 with a few updates:
https://github.com/kinecosystem/rewards-engine/pull/93

There were many other pieces of feedback which we have heard, but are choosing not to action on at this time.  

- Developers should be rewarded higher for improved spend opportunities in the their app.  

While we agree that rewarding developers with best spends would be ideal, one of our biggest learnings over the past 1.5 years of operating the KRE has been that anything with subjective monitoring is very hard to maintain given our ecosystem’s resources. There is a large number of apps who make frequent changes and this problem will only grow in scale as the ecosystem grows.  

- The KRE payouts should be capped using the amount of Kin Bought by users or the BI Ratio

There have been several posts (like @Raketenernie's) which push in this direction. We've already mentioned needing to balance developer incentives with good economics, but there is another subtler point here. The current amount of Kin Bought by users is not an accurate representation of the amount of Kin that can be "absorbed" from KRE payouts. When Kin is bought by a user currently, it is almost always spent back to the app developer, and the developer can choose to sell this Kin.  If all Kin bought by users is always immediately spent, and developers sell all of this Kin, then the net impact on the market is actually zero Kin Bought. This is why we are pushing for a KRE which incentivizes developers to (on net) move Kin into user wallets and have them continue to spend this Kin in app.

**Comment by Raketenernie** [comment]
I did post a proposal on github about a work around for a "cap" by
introducing a "lock-in mechanism"

**Comment by hitwill** [comment]
Closed as V3 already implemented
