### ISSUE TITLE
Concern over KRE daily payout value cap.

### ISSUE THREAD

**Issue by CWftw** [kinecosystem/rewards-engine#94]
While we agree with much of the KRE 3.0, we are very concerned with the following suggested change: ““For Q1 2021, we recommend a daily payout cap of 250 million Kin or $USD 5000 in Kin, whichever is less.”

The current daily KRE allotment is 500M Kin with no value cap.  500M Kin is currently worth $12400 USD.  At current market Kin value (0.00002479), the immediate effect of these changes would be to reduce the monetary value of the KRE by 60%, and reduce the total daily KRE to just 201M Kin.

For the past year, Kin has been at a very low value, typically with 5 zeros after the decimal place, and as a result the monetary value of the KRE payouts were low as well.  After the KRE partners have supported Kin through the long legal battle with the SEC, it is unfair to deprive them of the benefits of Kin’s appreciation.

In addition to the immediate 60% decrease in KRE payout values, there are a number of other very negative scenarios which this proposed change could precipitate:

1. Scenario 1: Kin continues to appreciate, perhaps through listings on more exchanges.  However, the KRE partners do not benefit from this appreciation, receiving less Kin in proportion to the appreciation.  Furthermore, if the KRE partners continue to distribute a consistent (or growing) amount of Kin to users, the difference between received Kin and distributed Kin will shrink.  In fact, should Kin appreciate significantly, KRE partners may earn less than they distribute.
2. Scenario 2: Kin depreciates significantly, back to or even below the levels we saw over the past years.  However, now that the daily KRE is capped at 250M, rather than 500M, the value rewarded to KRE partners will be half of what it was.
3. Scenario 3: One or more very large apps join the KRE, at a scale which would dwarf any current KRE partner.  Despite the monopoly clause, this would cause massive dilution for all existing KRE partners.  In KRE 2.2, this dilution would likely be counteracted by a sharp rise in Kin price due to the notoriety generated by a well known app integrating it, such that even if a KRE partner’s share shrinks by 95%, this would be at least partially offset by market forces causing a 5x increase in price.  However, a $5,000 daily cap means that, should one or more major new KRE partners join, existing KRE partner shares would decrease significantly, and if the price of Kin were to rise, the number of Kin received would decrease further (see Scenario 2), resulting in a deflationary crisis.

The last concern is that of incentive.  Since the start of the KRE, it was in the best interests of all KRE partners for Kin to be as valuable as possible, because that value directly correlated to the value of their KRE payouts.  This reinforced good behaviour among and between KRE partners, with regard to Kin integration, public support for Kin, and acting responsibly when liquidating Kin on the markets.  However, with this change, it will be optimal for KRE partners for the value of Kin to be at $0.00002.  Any higher and the $5,000 cap will begin reducing the daily 250,000,000 Kin payout, which would reduce the profit margin (earned Kin minus distributed Kin).  This would lead to negative behaviours which will actually impede appreciation of Kin, since it is no longer in everyone’s shared interest that the price of Kin be as high as possible.

Our recommendation would be for the KRE to continue as it always has, without a monetary value cap at all, as a cap would distort and derange the KRE, Kin market, and the behaviours of KRE partners.  We believe that cutting the Kin supply in half, from 500M per day to 250M, is more than enough to drive further strengthening of the Kin price.

However, if Kin believes that a monetary cap is warranted, it should not be significantly less than the current effective $12400.  It is important to incentivize growth in the Kin ecosystem and markets.  As such, if a monetary value cap is to be implemented, we would suggest a $20,000 cap.  This would incentivize an ‘optimal’ Kin price of 0.00008, which is a good goal for the next quarter.

**Comment by dillontking** [comment]
I agree with the thrust of your logic. A USD daily payout cap seems antithetical to the ethos of Kin. The Foundation should not be concerned with over-incentivizing at this stage. The goal should be to make the KRE more equitable and predictable, while aligning every developer to participate in marketing the currency to make it as valuable as possible. A 250mm Kin reward per day can be sustained for up to 65 years based on the KF's allocation of tokens. That seems reasonable. Perhaps at some point applying an exponential decrease so that the KRE never runs out. Imposing a USD cap, as a knee-jerk reaction to perceived exploitation of the existing system, is like trying to treat a scraped knee with a plaster cast.

All that being said, I don't think that any app necessarily _deserves_ a certain level of compensation for supporting Kin through the tough times. Integrating Kin is a mutual agreement to fight (in sickness and in health) for a better digital future, not an act of altruism.

**Comment by Ghost-Type** [comment]
good discussion. i agree that arbitrary limits on rewards are not a good solution and could dissuade potential partners that wish to create value. that said, so far most have not been incentivized to create value, and arbitrarily handing out massive rewards to apps regardless of the amount of value they create is also not smart, and the kin foundation has a responsibility to act in the best interest of the economy above all else, which is also in the developers' best interests.

> For the past year, Kin has been at a very low value, typically with 5 zeros after the decimal place, and as a result the monetary value of the KRE payouts were low as well. After the KRE partners have supported Kin through the long legal battle with the SEC, it is unfair to deprive them of the benefits of Kin’s appreciation.

kin's low price actually resulted in larger sum Kin payouts than apps would have received otherwise, which means they benefit more from kin's appreciation than ever, and they aren't being deprived of benefitting unless they sold. if kin's price was higher this whole time apps would have just received less kin. 

> Since the start of the KRE, it was in the best interests of all KRE partners for Kin to be as valuable as possible, because that value directly correlated to the value of their KRE payouts. This reinforced good behaviour among and between KRE partners, with regard to Kin integration, public support for Kin, and acting responsibly when liquidating Kin on the markets.

this is actually the issue, they arent acting this way. for example, the top Kin app, rave, is airdropping kin to their users and then taking it back with a spend which they can access the features of even if their wallet is empty. they then take the rewards and sell them on the open market. by this logic the KRE has incentivized gaming the KRE, not creating valuable spends. no one can blame them for acting in their self-interests, they are right to. in fact the KRE should be designed around it, because it is basic game theory. 

i vote that incentives should be unlimited to drive that hunger for apps, but more strictly defined and evaluated so that optimizing for KRE rewards is synonymous with optimizing for the creation of real value. after all, “Show Me the Incentive and I’ll Show You the Outcome” - Charlie Munger

the issue here isn't reward limits, it's rewarding the wrong things.

**Comment by ghost-of-kinerra** [comment]
#99

**Comment by hitwill** [comment]
This cap was considered carefully, with a compromise being to use a volatility cap. (The KRE is constrained during times of volatile swings to reduce selling. (During price climbs and dips)
